/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/SolidView.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SolidView.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.006, 0]}>
        <mesh geometry={nodes.window_1.geometry} material={materials.white} />
        <mesh geometry={nodes.window_2.geometry} material={materials.color2} />
      </group>
      <mesh geometry={nodes.frame1.geometry} material={materials.white} position={[-0.01, -0.003, 0.21]} />
      <mesh geometry={nodes.frame2.geometry} material={materials.white} position={[0.016, -0.296, 0.226]} />
      <mesh geometry={nodes.glass2.geometry} material={materials.glass} position={[0.016, -0.296, 0.226]} />
      <mesh geometry={nodes.glass1.geometry} material={materials.glass} position={[-0.01, -0.003, 0.21]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0.001, 0.006, 0]} />
      <mesh geometry={nodes.frame2_p1.geometry} material={materials.white} position={[0.016, -0.296, 0.226]} />
      <mesh geometry={nodes.frame2_p2.geometry} material={materials.white} position={[0.016, 0.023, 0.226]} />
      <mesh geometry={nodes.screen_frame_half.geometry} material={materials.white} position={[-0.002, 0.006, 0]} />
      <mesh geometry={nodes.screen_glass1_half.geometry} material={materials.glass} position={[0, 0.006, 0]} />
      <mesh geometry={nodes.screen_frame_full.geometry} material={materials.white} position={[-0.002, 0.006, 0]} />
      <mesh geometry={nodes.screen_glass1_full.geometry} material={materials.glass} position={[0, 0.006, 0]} />
      <mesh geometry={nodes.bottomwhite.geometry} material={materials.white} position={[0, 0.006, 0]} />
      <mesh geometry={nodes.bottomblack.geometry} material={materials.black} position={[0, 0.006, 0]} />
      <mesh geometry={nodes.bottombeige.geometry} material={materials.beige} position={[0, 0.006, 0]} />
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid0_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid0_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour0_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour0_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid1_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid1_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour1_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour1_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]} scale={0.85}>
        <mesh geometry={nodes.grid1_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid1_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]}>
        <mesh geometry={nodes.contour1_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour1_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid2_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid2_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour2_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour2_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]} scale={0.85}>
        <mesh geometry={nodes.grid2_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid2_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]}>
        <mesh geometry={nodes.contour2_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour2_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid3_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid3_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour3_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour3_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid4_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid4_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour4_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour4_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]} scale={0.85}>
        <mesh geometry={nodes.grid4_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid4_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[0.016, -0.296, 0.226]}>
        <mesh geometry={nodes.contour4_down_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour4_down_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.grid5_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.grid5_up_2.geometry} material={materials.color2} />
      </group>
      <group position={[-0.01, -0.003, 0.21]}>
        <mesh geometry={nodes.contour5_up_1.geometry} material={materials.white} />
        <mesh geometry={nodes.contour5_up_2.geometry} material={materials.color2} />
      </group>
    </group>
  )
}

useGLTF.preload('/SolidView.glb')
